### ISSUE TITLE
window is undefined when using with nextjs

### ISSUE THREAD

**Issue by chiptus** [airgap-it/beacon-sdk#108]
**Describe the bug (current behavior)**
when using Taquito using the beacon sdk and nextjs, I get "window is undefined" error on the first render.
you can see it here: https://codesandbox.io/s/beacon-wallet-error-thyut?file=/pages/index.js

I tracked the error to here: https://github.com/airgap-it/beacon-sdk/blob/4fd7f85b3c3e5370c4105999a46498ff4480486b/src/transports/clients/PostMessageClient.ts#L74

**To Reproduce**
1. start a new nextjs project
2. install @taquito/beacon-walet
3. import it into your pages/index.js
4. run `yarn dev`

**Expected (correct) behavior**
`window` is undefined because the first render happens on the server-side. The fix would be IMO to have a setup function that checks for extensions and let the package user call it.

**Screenshots and/or logs**
![image](https://user-images.githubusercontent.com/1381655/102748807-911b9e00-436b-11eb-8297-b848dad3fb2c.png)

**Comment by AndreasGassmann** [comment]
Hi. Thanks for the issue and the steps to reproduce it.

I quickly clicked on your link, but for me there was no error:

<img width="725" alt="Screenshot 2020-12-21 at 09 31 20" src="https://user-images.githubusercontent.com/680814/102755862-4bf96b00-436f-11eb-8330-3ec002bb9758.png">

When I tried to fork the project it told me that I need to sign up, so as a signed-out user it might not use SSR.

It's strange that this error is thrown because we added a piece of code that should catch this error. It works in both the node.js test environment, but we also successfully used the beacon-sdk in a backend service as a proof of concept. https://github.com/airgap-it/beacon-sdk/blob/4fd7f85b3c3e5370c4105999a46498ff4480486b/src/MockWindow.ts

The reason we do this call automatically is because the collection of installed browser extensions is asynchronous through a ping/pong mechanism. So without this call on page load, there would be a couple hundred milliseconds of delay as soon as the user calls the setup method that doesn't have to be there in most cases.

In any case, the call should never fail with that error and we could potentially add another setup method that can be called by the user to override the default behavior.

**Comment by chiptus** [comment]
> I quickly clicked on your link, but for me there was no error:
I opened it in an incognito window and got the same. you don't need to look in the browser console, but in the terminal on the bottom right corner of the page

**Comment by AndreasGassmann** [comment]
I see, I was looking at the "console" tab output of codesandbox.io and that one was empty. I do see the error in the "terminal" tab. I'll look into it as soon as I have time.

**Comment by manangouhari** [comment]
Hi, has there been any progress on this? We're trying to use beacon in production with GatsbyJS and facing the same issue.

**Comment by chiptus** [comment]
@manangouhari as a workaround you can use dynamic imports `await import("@airgap-it/beacon")`

**Comment by AndreasGassmann** [comment]
I did not look into this so far. @manangouhari I checked out your project and switched to the auth flow branch. How / where can I trigger the error?

**Comment by manangouhari** [comment]
> I did not look into this so far. @manangouhari I checked out your project and switched to the auth flow branch. How / where can I trigger the error?

Hey, this error is triggered when I try to build the project. 

```
gatsby build
```

Thanks in advance for the help.

**Comment by AndreasGassmann** [comment]
@manangouhari Are you sure the problem is only related to beacon? I fixed some issues with the beacon-sdk locally, which got rid of the error stack traces, but the build still fails. I then even removed the beacon-sdk completely and did an `npm install` (see node modules on the left), but the error is still here:

<img width="1625" alt="Screenshot 2021-01-29 at 14 30 54" src="https://user-images.githubusercontent.com/680814/106280912-ca82db80-623e-11eb-81d9-1dfcf26b4d79.png">

**Comment by manangouhari** [comment]
> @manangouhari Are you sure the problem is only related to beacon? I fixed some issues with the beacon-sdk locally, which got rid of the error stack traces, but the build still fails. I then even removed the beacon-sdk completely and did an `npm install` (see node modules on the left), but the error is still here:


Thanks for looking into it @AndreasGassmann. You're indeed right, the error was being cause by Amplitude, not Beacon. Actually, I thought it was Beacon, because the lib was visible in the traceback. Apologies to have sent you on this wild goose-chase.

**Comment by AndreasGassmann** [comment]
@manangouhari Don't worry, with your repo I was able to track down some of the issues we had with the `window` usage. I was just confused when I finished fixing everything and it still didn't work.

So in the next release this is hopefully fixed from the beacon-sdk side.

**Comment by AndreasGassmann** [comment]
2.2.1 should include some fixes regarding the window object usage. Please try again and open another issue if the error is still there.
