### ISSUE TITLE
Cannot read property 0 of undefined

### ISSUE THREAD

**Issue by keefertaylor** [airgap-it/beacon-sdk#11]
Beacon SDK throws an error in the UI. See screenshot for UI error and logs.

My client application is pretty vanilla, using Taquito to send a contract invocation:
```
    const contract = await Tezos.wallet.at(VAULT_FACTORY_ADDRESS)
    const result = await contract.methods.makeVault([["unit"]]).send();
```

The above code works with a TezBridge signer, so I'm inclined to think the error is probably in Beacon. I suspect you'll need more debugging information about my setup, LMK how is best to get that to you.  

<img width="1792" alt="Screen Shot 2020-09-20 at 1 52 58 PM" src="https://user-images.githubusercontent.com/18271723/93785639-2d0a0200-fbe3-11ea-85c0-b62f57bc3a68.png">

**Comment by AndreasGassmann** [comment]
The error message handling in the extension is currently pretty bad. We basically just take the raw error and show it to the user. In many cases we could handle them and provide nicer errors, such as "Not enough balance", etc.

With that in mind, should the transaction work? Are you calling a valid contract with valid parameters, using a revealed account with enough funds? You can see contract call errors when you open the "network" tab of the background.js task in chrome and inspect the responses from the node. (But in theory, they should be displayed in the UI.)

A demo to reproduce the error would help most, but you can also post the relevant snippets (ideally including contract address) here, or send them via DM in slack.

Did you also try to use Thanos or AirGap Wallet to see if the issue might be in the extension, rather than the SDK?

**Comment by keefertaylor** [comment]
> Are you calling a valid contract with valid parameters
Yes

> a revealed account with enough funds
Yes

> Did you also try to use Thanos or AirGap Wallet to see if the issue might be in the extension, rather than the SDK?
Yes. I made sure that this code works with TezBridge

**Comment by pascuin** [comment]
@keefertaylor do you have an update on this, were you able to get it to work?

**Comment by pascuin** [comment]
Closing this for now
