### ISSUE TITLE
requestPermissions is pending when window is closed

### ISSUE THREAD

**Issue by ungarson** [airgap-it/beacon-sdk#135]
I get wallet using new DAppClient, and then I call wallet.requestPermissions, then I press close button in the opened window, and I then get the error, as you can see in the console (first 10 seconds)
<video src="https://user-images.githubusercontent.com/13982759/105700546-0bff4800-5f1a-11eb-8dc6-cd67c9477f08.mov"/>

But if I close the window itself (not by clicking the close button), then the requestPermissions is pending and I don't get any errors (last 10 seconds).
Is it a bug or do I miss something maybe?

**Comment by AndreasGassmann** [comment]
This is an open issue in the beacon-extension. It does not send an "aborted" error on close: https://github.com/airgap-it/beacon-extension/issues/15

In Thanos, this should work.

Please keep in mind: Because our protocol also works with wallets over the network, you might not always get an aborted message. Imagine the request being sent to AirGap Wallet, the user sees it, then closes the app or locks his phone. In this case, we cannot send back an "aborted" message, which means this promise will hang forever.

I don't really know how we can solve this, because "timing out" a request would also be bad. If the user wants to sign with a ledger or AirGap Vault, signing can easily take 1 minute or more.

Any thoughts?

**Comment by ungarson** [comment]
Ok, duplicated then. Sorry. Don't have any thoughts yet, I will try to handle it on my side.
