### ISSUE TITLE
"Thanos wallet not installed" when it's actually installed

### ISSUE THREAD

**Issue by ungarson** [airgap-it/beacon-sdk#137]
Any ideas why this happens and how I can prevent it?

<img width="1028" alt="Screenshot 2021-01-25 at 22 41 18" src="https://user-images.githubusercontent.com/13982759/105757068-8f428d00-5f5e-11eb-8fb2-f9366e6ce9ea.png">

I use Thanos version: 1.1.0 and Beacon-sdk of version 2.1.0

**UPD**: Right now it's ok. I guess, the reason of this was my low internet connection. But still... It's confusing. I guess, would be better if it said something like "Loading..." instead of "Wallet is not installed" when it's not clear yet if it's installed or not.
<img width="1028" alt="Screenshot 2021-01-25 at 22 48 47" src="https://user-images.githubusercontent.com/13982759/105758058-e5fc9680-5f5f-11eb-9bb8-19605f4a38f8.png">

**Comment by AndreasGassmann** [comment]
The problem is that, as far as I know, you can not query if a browser extension is installed. So what we do is that we send a ping and wait for a pong from the extension (for 1000ms). If the extension is not installed, we will never get a pong. So at some point we have to assume the extension is not installed.

During development I noticed that the pong sometimes comes back very late (eg. after 1s). I was not able to reproduce this, but it only happened when the chrome dev-tools were open.

Unless this happens to you consistently, or you can show me a way to reproduce this, I don't think there is much we can do.
