### ISSUE TITLE
Rejecting a permission request should clear local active peer

### ISSUE THREAD

**Issue by AndreasGassmann** [airgap-it/beacon-sdk#165]
**Summary**
When a wallet is selected in the pairing alert, we persist the connection to that wallet as the "activePeer". This is helpful if in case the page is refreshed between the initial connection and the permission request (which would otherwise result in the pairing alert being shown again).

However, if the user rejects the permissions, the active peer is persisted, so the next time any action is done, it will send it to the same peer.

**Describe the expected behaviour**
If the user rejects the permission request and there is not already an activeAccount that matches the peer, the activePeer should be removed.

**Describe your use case**
1. Click "permission request"
2. Select "Spire" in the wallet selection
3. You remember you wanted to pair Thanos, so you cancel the request in Spire
4. Click "permission request" again => Currently it sends another request to Spire, but we should be able to select any wallet now

**Comment by Necroskillz** [comment]
I would say that if you refresh the page before confirming/canceling, it should also show the pairing again because until the user actually confirms in the wallet, I wouldn't say that they successfully paired.

Currently, I use this workaround before the wallet is created (when not already connected at startup): `localStorage.removeItem(StorageKey.ACTIVE_PEER)` to ensure that pairing always happens.

**Comment by AndreasGassmann** [comment]
Will be included in 2.3.0
