### ISSUE TITLE
Reduce library size

### ISSUE THREAD

**Issue by asbjornenge** [airgap-it/beacon-sdk#189]
Hi there!

I'm one of the deveopers on https://tezid.net 🙌 We recently added `@airgap/beacon-sdk` and `@taquito/beacon-wallet` to our dapp. It resulted in a bundle size increase from 600kb -> 1.95MB 😳🙈 It's a React app using create-react-app.

Beacon is super awesome ✨ It was easy to integrate and has a great UI included. However, I do consider 1.3MB quite a heavy footprint for a wallet library 😅

Anything we can do to reduce the lib size?

**Comment by AndreasGassmann** [comment]
Hi, thanks for reaching out.

One of our core dependencies is [libsodium](https://github.com/jedisct1/libsodium.js). We need this dependency in many places. Most importantly for the encryption of the P2P and PostMessage channels, but also for utility methods like generating secrets and calculating hashes. In theory it might be possible to replace libsodium with another smaller library (or even webcrypto), but because the tezos client and most dApps and wallets in the tezos ecosystem also use libsodium, I don't think it makes sense to change this. Maybe the libsodium dependency itself could be changed to fit our specific (tezos) use case and remove all the methods we don't need. But I'm not sure how feasible this is and how big the benefit actually would be.

Other than libsodium, we only use 4 more dependencies, all of which are less than 10kb each (gzipped).

Looking at the internal code, I don't see definitive red flags that have to be addressed. Maybe the `DApp` and `Wallet` specific code could be put into their own separate packages. But because most of the code is shared, it looks like for dApps we would only be able to reduce the size by about 5% (of the internal code, not including dependencies). The wallet part could probably benefit a bit more, but that doesn't matter for dApps.

<img width="434" alt="bundle-size" src="https://user-images.githubusercontent.com/680814/114099461-14cdac00-98c3-11eb-9c37-61f3462605c7.png">

The UI that is included accounts for around 15% of the size of the sdk (again excluding dependencies). But because this is something that most dApps want, I don't think it should be a priority split the UI code into a separate package. Instead, we should make sure that tree-shaking works so if dApps don't use it, it will be removed during bundling.

I personally don't see much room for improvement, to be honest. Please let me know if I overlooked something.

Regarding your specific issue. Can you run a bundle analyzer to see where this is coming from? (eg. https://www.npmjs.com/package/webpack-bundle-analyzer). I don't see how the beacon-sdk and its dependencies could result in 1.35MB additional minified javascript. Also note that you might not need to include `@taquito/beacon-wallet`. This is only necessary if you want to use taquito for advanced contract calls. `@taquito/beacon-wallet` includes some taquito specific dependencies that the beacon-sdk doesn't need: https://bundlephobia.com/result?p=@taquito/beacon-wallet@8.1.0 vs https://bundlephobia.com/result?p=@airgap/beacon-sdk@2.2.3.

You can see an example of plain beacon-sdk vs taquito here: https://docs.walletbeacon.io/guides/simple-contract-call

**Comment by asbjornenge** [comment]
@AndreasGassmann thank you for a very detailed answer 🤩 

Looks like you are correct that `@taquito/beacon-wallet` adds even more weight than just `@airgap/beacon-sdk` 👍 I will def. look into using beakon-sdk directly which should cut almost 300k from my bundle 👌 In frontend ops terms that is significant savings!

Have you looked into making a custom build of libsodium to include only the features you need? If that could shave another 100k it would def. be worth looking into imho ⚡

**Comment by AndreasGassmann** [comment]
We'll have to look into the custom build of libsodium. One thing we have to consider is that many people use taquito. So unless taquito uses the same custom build, there might be code duplication from the libsodium library. At the moment we synchronise the version with taquito so it can be shared.

**Comment by asbjornenge** [comment]
Alright, thanks for providing lot's of good information and details here 🙌 I'll close the issue 👍
