### ISSUE TITLE
Custom RPC Node Sensing 

### ISSUE THREAD

**Issue by sebuhbitcoin** [airgap-it/beacon-sdk#208]
**Summary**
A short description of the new feature.

I want to use my custom RPC on all beacon wallet powered dapps.

**Describe the expected behaviour**

when i click connect wallet button, beacon checks if i have a custom rpc selected in my wallet of choice.
After sensing my custom rpc, beacon wallet connecting changes all rpc requests from the dapp to go thru my custom rpc only.

**Describe your use case**
A clear and concise description of how the new feature could be used.

when the network is getting congested i want to be using my custom rpc to help alleviate congestion and speed up my connection. 

**Additional context**

Thank you for considering my feature request.

**Comment by AndreasGassmann** [comment]
Thanks for your feature request.

This would be very useful. Currently, every dApp has to manually add an option to change the node that is being used, and as far as I know, tezos.domains is the only dApp that actually allows you to do that. If we added this functionality on the beacon level, it would make it much easier.

However, beacon doesn't actually include or connect to any RPC nodes. It's usually taquito that does it.

From the beacon side, the RPC url can already be shared by the wallet as part of the permission request. Currently, Spire and AirGap do not allow you to change that and will just use the one that was provided by the dApp (in the request). I'm not sure about other wallets.

So as soon as wallets would be updated to allow this, the dApps could get the "rpcUrl" defined in a permission response and instead use that one. I'm not sure if we can enforce this, but maybe taquito could internally handle that. But we'll also have to think about the security implications of this.

I'll reach out to the other projects and discuss it with them.

**Comment by jevonearth** [comment]
I'm more conservative about this proposed feature. I don't think the dApp should be able to dictate the RPC used by the wallet. We have dapps and wallet concerns separated for this reason. 

I do think that wallets, generally, should allow users to change which node they want to use and that wallets should ship with RPC defaults that are reliable and trusted. 

The node that Dapps use is completely up to the dapp. What tezos domains did, allowing users to choose a node, or provide a custom node, is superb. Offers a good default, choice for alternative, and custom node for power users.

**Comment by AndreasGassmann** [comment]
> I'm more conservative about this proposed feature. I don't think the dApp should be able to dictate the RPC used by the wallet.

I think he wants to have it the other way around. Basically setting a custom RPC in the wallet, and then having the dApp use that one (if a custom one is set).

> We have dapps and wallet concerns separated for this reason.

The dApp can actually pass an RPC to the wallet in the permission request. Spire will then do all operations related to that account through that RPC. This was always the intention, even though the wallets are free to stick to their own RPC if they want.

---

With the focus here being on setting the RPC in the dApp and not in the wallet (if you have concerns with that, we can discuss them in a separate issue), do you still have concerns? Security wise it shouldn't have an impact because the wallet can be trusted in any case.

What I would like about this feature is that you are making dApps more decentralised. I remember how we had a few issues with giganodes some time ago, and many of our dApps (tzcolors, tzbutton) were basically down for a certain period of time. The only thing we could have done was re-deploy with a different RPC hardcoded (or let the user choose on our website). By allowing users to set the RPC "from their wallet", it would be much more flexible.

**Comment by jevonearth** [comment]
> With the focus here being on setting the RPC in the dApp and not in the wallet

Understood, thanks for clarifying!

One challenge will be RPC services that are restricted by CORS. For example, a kukai wallet may use its own dedicated RPC that will be configured to only allow requests coming from Kukais official URL. This could be enforced by CORS. I anticipate we will see more dedicated RPCs that are scoped to dApps, as the single dominant public RPC pattern has issues.

- If a Wallet hints to the dapp "Use this RPC", how will the dapp determine if that RPC works for it? 
- If the Wallet does pass an RPC that is not operable in the dapps context, how will the dapp fail gracefully? 

I don't think we should rely on the dApp user to fix this type of condition by adjusting settings.

**Comment by sebuhbitcoin** [comment]
Thank you for responding to my Feature request. Temple Wallet has already added this feature request and it has made my experience on many platforms much better.
