### ISSUE TITLE
Display version number

### ISSUE THREAD

**Issue by pikatos** [airgap-it/beacon-sdk#246]
**Summary**
We should have a way to know which version of the SDK a dApp is using.

**Describe the expected behaviour**
I would like to know which version of the Beacon SDK is used by the dApp I'm interacting with. This could be achieved by displaying a version number in the wallet selection modal or maybe in every modals.

**Describe your use case**
As a dApp developer I would like to know if I'm using the correct version of the SDK.
As a wallet developer I would like to know if a dApp is using a recent enough version to be compatible with the wallet I'm working on.

**Additional context**
It could be interesting for bug reporting too.

**Comment by AndreasGassmann** [comment]
The SDK version is written to localStorage, developers can easily inspect it there.

As for adding it to the UI, I'm not sure how relevant it is for regular users to see this. Even when issues are reported, it's easy for developers to simply check what version that dApp is currently using, either by inspecting the localStorage, or by checking this list: https://docs.walletbeacon.io/dapps

Does that work for you, or would you still prefer to have it in the UI because of some other use case?

**Comment by pikatos** [comment]
It's good enough for me.
