### ISSUE TITLE
Disconnect functionality doesn't work properly

### ISSUE THREAD

**Issue by gdsoumya** [airgap-it/beacon-sdk#255]
**Describe the bug (current behavior)**
When I create a new client and call the `destroy()` function on it to disconnect my wallet, the next time I try to connect the beacon popup says that Temple wallet is not installed even though it's there. Clearing the cache from the browser manually fixes this issue.

**To Reproduce**
1. create a client
2. get the permission to connect to a wallet
3. beacon pop up appears, select temple wallet
3. call `destroy()` on the client
4. refresh the page
5. repeat step 1 & 2
6. should pop up the beacon wallet options with the Temple wallet marked as not installed.

**Expected (correct) behavior**
Re-connection will  after a `destroy()` call will show Temple wallet as available and installed.

**Screenshots and/or logs**
If applicable, add screenshots or logs to help explain your problem.
![bug](https://user-images.githubusercontent.com/44349253/128902819-d2d5a49a-4aa7-4209-b8c4-36499a2127a8.png)

**Environment**

- Device: Laptop
 - OS: ubuntu 20.04
 - Browser: brave

**Comment by AndreasGassmann** [comment]
Hi. I did not yet have time to look into this, but could you please explain your use-case? Calling `destroy()` manually is almost never what you want. Even calling `disconnect` is actually not something that most dApps want.

If you simply want to bring the dApp back to a state where the user can connect to another wallet/account, you can just call `client.clearActiveAccount()`. That covers basically every use case I have encountered in the dApps I was working on.

A "connection" in beacon is in a way just the fact that both peers are aware of the other peers' public key so they are able to see and send messages. But it's not like there is an active HTTP or WebSocket connection open for every wallet that you connect to (if that's what you are worried about).

The `destroy` method is something very specific if you want to _completely_ reset the SDK, which is basically the same as wiping the localStorage.

If you can tell me exactly what your use case is I'll be able to let you know the best way to do it. But in any case, I'll look into this issue because it shouldn't be happening.

**Comment by gdsoumya** [comment]
The clearActiveAccount call doesn't give me the option to choose a
different wallet. I need the initial beacon popup to choose a wallet which
only appears when I call destroy()

**Comment by AndreasGassmann** [comment]
> The clearActiveAccount call doesn't give me the option to choose a different wallet.

The "clearing" of the account will not show the popup again directly because it will just clear the internal state. But the next time you do a permission request, it will be as if it was the first time the user visits the dApp. I am 100% sure that this works because we use it in all of our dApps. Check https://tzcolors.io as an example. You can connect a wallet, then you click on the address and select "disconnect". This will call "clearActiveAccount". After thatthe button changes back to "Connect Wallet" and when you click it, you will get the wallet selection alert again.

I'm currently on mobile so I cannot give you a detailed snippet, but this is from the docs and should do what you need. You should call this code every time someone interacts with Beacon. And if at any point, somewhere in your dApp you call `await client.clearActiveAccount()`, the next time the snippet is executed it will show you the popup.

```ts

const dAppClient = new DAppClient({ name: "Beacon Docs" });

let myAddress: string | undefined;

// This code should be called every time the page is loaded or refreshed to see if the user has already connected to a wallet.
const activeAccount = await dAppClient.getActiveAccount();
if (activeAccount) {
  // If defined, the user is connected to a wallet.
  // You can now do an operation request, sign request, or send another permission request to switch wallet
  console.log("Already connected:", activeAccount.address);
  myAddress = activeAccount.address;
} else {
  // The user is not connected to a wallet (either because it's a new user or because the activeAccount was cleared)
  const permissions = await dAppClient.requestPermissions();
  console.log("New connection:", permissions.address);
  myAddress = permissions.address;
}
```

**Comment by gdsoumya** [comment]
Thanks that seems to be working. Not sure why but when I tried last time it was not giving the popup next time I tried to connect, could be due to some other issue. 

I think my issue to disconnect the wallet has been resolved, but we can keep this open if you are still investing the `destroy()` call.

**Comment by AndreasGassmann** [comment]
I will close this issue because the initial problem has been addressed.
