### ISSUE TITLE
Allow disabling of wallets in Beacon

### ISSUE THREAD

**Issue by burk3** [airgap-it/beacon-sdk#258]
**Summary**
We need to disable Galleon since it does not support `signRequest`s at all. A straightforward way to enable this would be to allow a consumer of the Beacon SDK to specify wallets that should be disabled in the modal.

**Describe the expected behaviour**
As a dapp developer I'd like to be able to do something like this:
```javascript
const dAppClient = new DAppClient({ name: "Beacon Docs", disabledWallets: ["galleon_desktop"]});
```
The result would be Galleon being greyed out or absent from the Beacon modal, even if it is present on the user's system.

**Describe your use case**
Our app needs `signRequest(MICHELINE)` functionality in order to authenticate a DID (a 3id DID to be specific). Galleon is the only wallet that does not support it.

**Comment by AndreasGassmann** [comment]
This is currently not possible. I'm also a bit hesitant to add this because beacon is built around the idea of giving users complete freedom over what kind of wallet they use. Even if we would allow the disabling of wallets, a determined user will always be able to pair any wallet he wants, for example by scanning the QR code or copy/pasting the pairing code. So disabling a wallet will not really solve the issue you are trying to solve.

Looking at it from a Galleon user perspective, it would also be very confusing if I opened your dApp and then get a beacon pairing alert where my wallet was missing. My first instinct wouldn't be to think that the wallet is not compatible, but rather that there is some kind of issue on my end. So _if_ we allow disabling of wallets, we'll have to still display them, but disable them and ideally even provide a message like "This wallet is not compatible with this dApp".

In my opinion, the dApp should not control what wallet the user can use. Instead, the dApp should either make use of the permission scopes that are given during the permission request (eg. display an error if the `sign` scope is not given), or it should let the wallet inform the user that a request can't be handled. I don't know what Galleon does when it receives a signRequest, but I would assume that the user is informed that the request cannot be handled.

If a wallet can easily be disabled by the dApp developer, it will also make it harder for wallets to react and update. In case Galleon pushes an update, they will have to reach out to all dApp developers that disabled their their wallets and have them update their apps, which is a cumbersome process (and speaking from experience, dApp developers are often quite slow to update their dApps).

Any thoughts on this?

**Comment by burk3** [comment]
> So if we allow disabling of wallets, we'll have to still display them, but disable them and ideally even provide a message like "This wallet is not compatible with this dApp".

This sounds acceptable. Currently, the user experience is goes something like this if a user selects Galleon, which sounds even more confusing due to the complete lack of feedback for the user:

1. Beacon modal pops up
2. user clicks Galleon
3. Galleon asks to connect with dApp (user clicks Connect)
4. Galleon asks for sign permissions for dApp (user clicks Allow)
  ![image](https://user-images.githubusercontent.com/81054/131886441-74412029-e839-4254-a31f-86037a663e50.png)
5. dApp sends signing request and hangs because Galleon just never responds

>  Instead, the dApp should either make use of the permission scopes that are given during the permission request (eg. display an error if the sign scope is not given)

So if I'm understanding this proposal correctly, the flow for a wallet that doesn't support signing (e.g. Galleon, at least according to the table) would go something like this:
1. dapp requests "sign" scope
2. beacon modal pops up, user selects Galleon
3. Beacon talks to galleon running locally asking to connect, user sees Galleon connection request and hits "connect"
4. Beacon talks to galleon running locally asking for permissions for the "sign" scope. Galleon responds with "I can't do that" (?)
5. Beacon throws some kind of `UNSUPPORTED_SCOPE` event that the dapp catches and uses to display some more info on the issue, or Beacon itself shows the unsupported notification.

I get the impression that there is no mechanism currently for a wallet to respond with something like `UNSUPPORTED_SCOPE`, or if there is then it's not implemented in Galleon.

We would be fine with either of these solutions. It sounds like the first one mentioned (allow dApp to grey-out an unsupported wallet with standard message) would be the quickest, while the second would be the ideal solution but would take much more effort (to update the protocol and get buy-in from wallets).

**Comment by AndreasGassmann** [comment]
Sorry for the late response.

Due to the feedback we received over the last months, I think we have to implement this feature. 

I think we'll go with an API similar to what you proposed. We may also add the option for the developer to specify a reason why the wallet is disabled.

```typescript
const dAppClient = new DAppClient({ name: "Beacon Docs", disabledWallets: ["galleon_desktop"]});

// or

const dAppClient = new DAppClient({ name: "Beacon Docs", disabledWallets: [{ id: "galleon_desktop", reason: "Does not support message signing."}]}); // The UI would show something like "This wallet has been disabled for the following reason: 'Does not support message signing'"
```

As a sidenote, in the near future we might have to change the layout of the popup because as more wallets get added, the list will become too big. So we will have to think about how we can solve that and we will also take this issue into consideration.

---

To answer your questions:

> 4. Beacon talks to galleon running locally asking for permissions for the "sign" scope. Galleon responds with "I can't do that" (?)

Yes. If the wallet is not able to handle "sign" requests, it should not give this permission. The dApp can then check in the permission response if the requested permissions were given and handle the case if it is not given.

> Beacon throws some kind of UNSUPPORTED_SCOPE event that the dapp catches and uses to display some more info on the issue, or Beacon itself shows the unsupported notification.

There is currently no such error, but it would be a good idea. The whole scope/permission system should be improved, now that we have learned about some additional use cases. We might tackle that in v3 because it might be requiring breaking changes.

**Comment by madztheo** [comment]
> Sorry for the late response.
> 
> Due to the feedback we received over the last months, I think we have to implement this feature.
> 
> I think we'll go with an API similar to what you proposed. We may also add the option for the developer to specify a reason why the wallet is disabled.
> 
> ```ts
> const dAppClient = new DAppClient({ name: "Beacon Docs", disabledWallets: ["galleon_desktop"]});
> 
> // or
> 
> const dAppClient = new DAppClient({ name: "Beacon Docs", disabledWallets: [{ id: "galleon_desktop", reason: "Does not support message signing."}]}); // The UI would show something like "This wallet has been disabled for the following reason: 'Does not support message signing'"
> ```
> 
> As a sidenote, in the near future we might have to change the layout of the popup because as more wallets get added, the list will become too big. So we will have to think about how we can solve that and we will also take this issue into consideration.
> 
> To answer your questions:
> 
> > 4. Beacon talks to galleon running locally asking for permissions for the "sign" scope. Galleon responds with "I can't do that" (?)
> 
> Yes. If the wallet is not able to handle "sign" requests, it should not give this permission. The dApp can then check in the permission response if the requested permissions were given and handle the case if it is not given.
> 
> > Beacon throws some kind of UNSUPPORTED_SCOPE event that the dapp catches and uses to display some more info on the issue, or Beacon itself shows the unsupported notification.
> 
> There is currently no such error, but it would be a good idea. The whole scope/permission system should be improved, now that we have learned about some additional use cases. We might tackle that in v3 because it might be requiring breaking changes.

I would like to bring this topic to light again as the problem still stands and we are facing a similar issue on our project at the moment. We are using the Beacon Wallet through the Taquito library to let our users connect their Tezos wallet to our dapp. Most of these users are not crypto native and are pretty new either to the field in general or Tezos more specifically. So a lot of them end up creating their first Tezos wallet when going through the signup process on our web app. And some chose Galleon without knowing that it cannot be used with dapps as it doesn't support signing messages or transactions. Wondering why it was in the list of displayed wallets in the first place.

The solution mentioned above seems the right way to go, by giving the developer more flexibility as to which wallets to display. However now in 2023, the feature is still not here. If it does require breaking changes and cannot be done quickly, then I would at least suggest removing Galleon altogether from the list in the meantime. Cause I don't see the use case of Galleon being given as an option.

**Comment by AndreasGassmann** [comment]
This feature, in some form, will be part of the pairing alert redesign discussed here: https://github.com/airgap-it/beacon-sdk/issues/355

The pairing alert redesign is now one of our highest priority tasks, so we'll should soon have some progress here.

---

As a small side note, most Galleon versions do support beacon, see my latest comment here: https://github.com/airgap-it/beacon-sdk/issues/437

**Comment by AndreasGassmann** [comment]
In the latest version the "featured" wallets can now be specified. It's not possible to disable wallets, but seeing the non-featured wallets requires an extra step to see the list of all wallets. This should allow developers to specify which wallets they  want to suggest to users, while still giving more advanced users access to their favorite wallets. Feel free to re-open this issue if disabling of wallets is still a requirement on your side.
