### ISSUE TITLE
Matrix failing to create room

### ISSUE THREAD

**Issue by simonmcl** [airgap-it/beacon-sdk#267]
**Describe the bug (current behavior)**
Sometimes Beacon will fail to pair with a wallet. Open the console and you will see an error that Matrix returned a HTTP 500 when trying to create a room.

**To Reproduce**
The issue is random, and I don't have an exact repro steps. I've seen it frequently while doing the below.

HD wallet with 6 sub accounts. Open wallet in one tab, and 6 dApps in different tabs (e.g. quipu swap, pixelpotus, crunchy, plenty etc.). One by one try to connect all the dApps to different sub accounts (i've been using the "other" QR code option and pasting the code across).

Frequently one or more of the connections will fail, with no error, no message, no permissions dialog. It just fails silently. Open the console to find a HTTP 500 on `.../_matrix/client/r0/createRoom` with an error: 

```
Error: Uncaught (in promise): Object: {"errcode":"M_UNKNOWN","error":"Internal server error"}
```

**Expected (correct) behavior**
Should connect or display an error with "retry"

**Environment**

- MacOS 11.4
- Brave or Safari

**Additional context**
Have seen it happen sporadically with many different setups, both single accounts and HD wallet with many accounts.

**Comment by AndreasGassmann** [comment]
Thanks for opening the issue.

My assumption currently is that this is somehow related to rate limits. I will try to reproduce it locally.

If it happens again, could you please tell us which node you were connected to and the exact time it happened? Then we could try to check the server logs for some additional information.

**Comment by simonmcl** [comment]
@AndreasGassmann had it happen a few times today. 2 Different wallets, a few times each.

First wallet cancelled and retried the connection request 3 - 4 times before it was successful. This was around 10:42 am GMT+1. Second Wallet generated the same error twice, roughly 10:45 am GMT+1.

```
beacon-node-1.sky.papers.tech/_matrix/client/r0/createRoom

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
main-es2015.80f77e15c1d12dbdff5b.js:1 ERROR Error: Uncaught (in promise): Object: {"errcode":"M_UNKNOWN","error":"Internal server error"}
    at k (polyfills-es2015.1bccf70f83928af9d62e.js:1)
    at polyfills-es2015.1bccf70f83928af9d62e.js:1
    at c (main-es2015.80f77e15c1d12dbdff5b.js:1)
    at l.invoke (polyfills-es2015.1bccf70f83928af9d62e.js:1)
    at Object.onInvoke (main-es2015.80f77e15c1d12dbdff5b.js:1)
    at l.invoke (polyfills-es2015.1bccf70f83928af9d62e.js:1)
    at s.run (polyfills-es2015.1bccf70f83928af9d62e.js:1)
    at polyfills-es2015.1bccf70f83928af9d62e.js:1
    at l.invokeTask (polyfills-es2015.1bccf70f83928af9d62e.js:1)
    at Object.onInvokeTask (main-es2015.80f77e15c1d12dbdff5b.js:1)
```

**Comment by pascuin** [comment]
Thanks for providing more information. Are you using a VPN by any chance?

**Comment by simonmcl** [comment]
@pascuin no VPN or any kind of special network setup

**Comment by klassare** [comment]
I'm also observing the internal server error on the join request

![Screenshot_48](https://user-images.githubusercontent.com/31806893/155579951-ee85c937-0e57-4f04-b5e7-9c6269209fa2.jpg)
![Screenshot_47](https://user-images.githubusercontent.com/31806893/155579960-ebbd6054-b863-4df1-9a88-ef6757bdcf8b.jpg)

**Comment by AndreasGassmann** [comment]
After upgrading the matrix servers to a newer version years ago, I think we have not seen this error anymore. If it still exists, feel free to re-open the issue.

**Comment by simonmcl** [comment]
@AndreasGassmann / @pascuin bump bump

**Comment by simonmcl** [comment]
@AndreasGassmann / @pascuin / @jsamol bump bump bump

**Comment by AndreasGassmann** [comment]
Hi @simonmcl. Yes, this was investigated at the time. It was a long time ago, so I don't remember the specifics nor the exact timelines. But IIRC, around that time, we had a few issues with the matrix servers, especially under heavy peak load (eg. NFT drops). Because of this, we updated our matrix nodes, which increased performance a lot. While we did those updates, the fact that we used different matrix node versions across our network, did result in incompatibilities between room versions, which in turn resulted in problems when users from older servers were invited to newer users. Again, it was a long time ago, I'm not sure if that was related to your issue.

The problem with the error you posted is that the 500 error doesn't give us much information as to what happened. While our nodes were unstable, it is likely that this issue caused some of those 500 errors: https://github.com/matrix-org/synapse/issues/2047.

At the time, we did not have verbose server logs enabled because IIRC they were affecting server performance. I remember how we did enable them on some servers for testing for some time, but we then disabled it again when most of the issues were resolved.

So to summarise: Yes, we did investigate, but we did not find a clear answer because there were not enough server logs and we were not able to reproduce it. The updating of the nodes seemed to make things a lot better.

> Do you have some sort of logging/reporting on your side to confirm that this has been fixed?

As you said yourself, the issue could not be reproduced and happened randomly, so there is no way to confirm that is was fixed.

> Beacon connection issues are still a weekly or sometimes daily complaint from users, i'm not sure if its this specifically, but something is still broken.

I still work with beacon on a daily basis and I don't remember when I had a 500 error on a /createRoom endpoint in a very long time. I personally don't think that the connectivity issues are related to this specific issue.

There are two problems that are more likely to cause those issues:
1. Browser tab to browser tab communication on mobile devices is unreliable. Tabs get suspended when put in the background, depending on the phone settings or battery life. If the dApp tab is suspended while the wallet is loading and the beacon request is being handled / responded to, the connection will fail. Using a mobile app instead of having a web-based wallet does seem to improve this behaviour. We are also looking into changing the protocol to get rid of the 2 roundtrips that are required to establish a connection. But this is a big change with many implications, so I'm not sure if it's even possible. But we are looking into it.
2. Depending on the location of the user around the world, the additional lag when communicating with our servers can amplify the above problem. We are trying to set up nodes around the world to improve this.
