### ISSUE TITLE
Max Listeners Exceeded

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#268]
**Describe the bug (current behavior)**
After adding 10 (can vary between devices/browsers) peers, it is no longer possible to add more peers. It will just silently fail, with no permission request showing up in the wallet.

**To Reproduce**
1. Go to kukai.app
2. Pair with a dapp
3. Repeat step 2 until you see a warning in the dev console

**Expected (correct) behavior**
Users must be able to connect with as many dapps (peers) as they want.

**Screenshots and/or logs**
![exeededLimit](https://user-images.githubusercontent.com/31806893/133978264-36291ed3-e556-42d5-b741-f97f58aa52e5.png)

**Environment**

 - Browser Chrome

**Additional context**

**Comment by AndreasGassmann** [comment]
Thanks for the report.

Looking through the documentation of "EventEmitter", it looks like this message is only there to warn users of a _potential_ memory leak. In our case, those listeners, one per connected dApp, are intentional. There is no problem with this behaviour if the listeners are set up on purpose.

I will still try to reproduce the issue locally, because the functionality should not be affected.

**Comment by klassare** [comment]
Closing this since it's not reproducible. We received user reports that it didn't work, but started to work after removing some peers. The problems must have been unrelated to this warning.
