### ISSUE TITLE
requestPermissions error with Nextjs

### ISSUE THREAD

**Issue by maninkari** [airgap-it/beacon-sdk#344]
Hi, 
I am trying to use the DAppClient with Nextjs.
I am able to create to DAppClient object but when I console.log it it doesn't seem to have a `requestPermissions` method and I keep getting the following error: 
```
error:  TypeError: Cannot read properties of undefined (reading 'call')
```
Sounds like an error while resolving the promise but I don't know how I could fix it. Here's my code, 'Got permissions...' message gets never printed. 
 
```
useEffect(() => {
    const connect = async () => {
      dAppClient = new DAppClient({ name: 'Beacon Example' })
      console.log('dAppClient: ', dAppClient)
      try {
        const permissions = await dAppClient.requestPermissions()
        console.log('Got permissions', permissions.address)
      } catch (e) {
        console.log('error: ', e)
      }
    }
    connect()
  }, [])
```

I tried using only taquito and got basically the same result: an object initialised, apparently without the requestPermissions method and the same error message when trying to request permissions.

"@airgap/beacon-sdk": "^3.0.0
"@taquito/beacon-wallet": "^12.1.0"
"@taquito/taquito": "^12.1.0"
  
Thank you!

**Comment by AndreasGassmann** [comment]
Hi. Sorry for the late reply. I'm assuming this issue is no longer relevant because it has been a long time. Feel free to reopen if it's still an issue.

There were other users that were able to get the beacon-sdk working with nextjs. My initial thought would be that the code might be executed on the server side (SSR), which could be the cause of the issue.
