### ISSUE TITLE
No event for "Cancel Request" link in showSentToast

### ISSUE THREAD

**Issue by Naggertooth** [airgap-it/beacon-sdk#366]
I have to modify UI with addEventListener with custom comparison instead of using events due to no event provided on this action...
![image](https://user-images.githubusercontent.com/24671211/172960588-0ec9f2b7-d8c7-4048-a07c-1f2a45ced989.png)

Would be cool, if it would trigger cancellation of transaction or contract call or else relevant actions.
Just like if i will click on Reject in transaction confirmation window 
![image](https://user-images.githubusercontent.com/24671211/172960492-9421e650-6840-4b3c-ab5a-97e20faa1c56.png)

**Comment by AndreasGassmann** [comment]
I agree that it makes sense to expose the "Cancel" action callback to the user, that's something we can add in a future release.

**Comment by AndreasGassmann** [comment]
We decided to remove the "Cancel Request" option from the modal. It didn't really make sense, because the wallet potentially already received the request, and there is no way to know if the wallet would still handle it or not. The only way would be to introduce a new "request_abort" message type or something like that, but that also wouldn't make sure the request is not handled under any circumstance. So it's cleaner to just remove it as it was always intended to just hide the UI.
