### ISSUE TITLE
Get 'true' account, avoid spoofing?

### ISSUE THREAD

**Issue by hitthefloor1** [airgap-it/beacon-sdk#368]
This is more of a question, how do we 'get' the 'true' account everytime? Since the activeAccount or any other returns can be easily spoofed using dev tools or injections, should we just make a new permission request everytime? Using it just for authentication purposes, not interacting with the blockchain, thanks.

**Comment by hitthefloor1** [comment]
Any other ideas to get 'real' account, while not using contracts or avoiding spoofing?

Appearantly permissions.address can be easily spoofed also, well client.getWalletInfo() does a nice job, couldn't spoof it (I'm new), can I rely on it while applying some checks/logic?

**Comment by AndreasGassmann** [comment]
Hi. Thanks for your question and sorry for the late reply.

The address (or public key) that is contained in a permission response can always be spoofed, it cannot be used to verify ownership of an account. The only way a user can *prove* that he is the owner of an account, meaning he has the private key that corresponds to an address/public key, is to ask him to sign a message.

To do this, you can use the following flow (which will require a backend):

1. Do a permission request, the wallet will return a public key / address.
2. Send the public key and address to your backend and have your backend return a "challenge" or message that has to be signed by this message. Usually, this challenge should contain a timestamp, the URL of your dApp, as well as some random string of data. (eg. "25-06-2022_mydapp.com_g29gdu3").
3. Your dApp then sends a request to the wallet to sign this data with the private key that corresponds to the the account that was shared. (See https://tezostaquito.io/docs/signing/#generating-a-signature-with-beacon-sdk)
4. Once you receive the signature from the wallet, you send it to your backend where your server verifies that the signature is correct and corresponds to the account. If everything is correct, you know the user is the owner of that address. You can then consider this user authenticated.

If the user ever reconnects, you can check the session of your backend and depending on your logic, you may ask the user to re-authenticate by signing another message after some time.

---

And just to make it clear, basically everything that your dApp sees can be spoofed by someone who has control over the dApp, or even the wallet. To illustrate this, you can use our debug wallet, which allows you to connect to a dApp using a different account. This is very helpful for debugging issues users have on your dApp (because you can basically have a "view only" version of what they see), but obviously you will not be able to sign anything. You can access the debug wallet here: https://debug.walletbeacon.io

Let me know if you have any other questions!

**Comment by AndreasGassmann** [comment]
I'm going to close this, feel free to re-open if you have further questions.
