### ISSUE TITLE
Could not resolve libsodium-wrappers

### ISSUE THREAD

**Issue by xsfunc** [airgap-it/beacon-sdk#380]
**Describe the bug (current behavior)**
Can't run dev server on vitejs
Get error when `npm run dev`

**To Reproduce**

1. Use vitejs template for react 
`npm create vite@latest my-app --template react`
2. import beacon sdk
`import { DAppClient } from '@airgap/beacon-sdk'`
3. try to connect wallet

**Screenshots and/or logs**
```
[
    {
      detail: undefined,
      id: '',
      location: {
        column: 133,
        file: 'node_modules/@airgap/beacon-transport-matrix/dist/esm/communication-client/P2PCommunicationClient.js',
        length: 20,
        line: 10,
        lineText: "import { ready, crypto_generichash, from_string, crypto_sign_detached, crypto_secretbox_NONCEBYTES, crypto_secretbox_MACBYTES } from 'libsodium-wrappers';",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "libsodium-wrappers" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "libsodium-wrappers"'
    }
  ]
```
if I add libsodium-wrappers as external package I get follow error:
`Cannot read properties of undefined (reading 'sodium')`

**Comment by jfbloom22** [comment]
This workaround resolved it for me:  https://github.com/ecadlabs/taquito/issues/882#issuecomment-1075096459. 
I used beacon-sdk version 3.1.3.  

There is still a potential issue with how the libsodium-wrappers dependency is included in the beacon-sdk.  Something about it causes Vite to have an issue when serving the app in dev mode.  To be clear, this workaround only effects dev mode in Vite.  Build works out of the box.   Since it does not effect the production build, it is not a horrible workaround.  

Anyone have any insight into what might be special about how the libsodium-wrappers dependency is included?

**Comment by AndreasGassmann** [comment]
I don't know why libsodium-wrappers is giving so many issues, but we're trying to replace it to get rid of those issues once and for all.

**Comment by AndreasGassmann** [comment]
Beacon SDK version `3.2.0` no longer uses libsodium, please give it a try.
