### ISSUE TITLE
Hexadecimal representation of SigningType.RAW is wrong.

### ISSUE THREAD

**Issue by Gau-thier** [airgap-it/beacon-sdk#383]
**Describe the bug (current behavior)**
The hexadecimal representation of a RAW payload is missing the first character.
For example, if I submit:

```typescript
const response = await dAppClient.requestSignPayload({
  signingType: SigningType.RAW,
  payload: "any string that will be signed",
});
```

The hexadecimal displayed in the Temple popup is:
`16e7920737472696e6720746861742077696c6c206265207369676e6564`
If I decode this hexadecimal to a string, I obtain:
`ç7G&ærFBvÆÂ&R6væV` which is not at all the one I provided.

The correct hexadecimal representation of `any string that will be signed` is:
`616e7920737472696e6720746861742077696c6c206265207369676e6564`
yours is:
`16e7920737472696e6720746861742077696c6c206265207369676e6564`
We can see the first `6` is missing in your hexadecimal representation.

**To Reproduce**
You can reproduce this behavior within your [own documentation about signing](https://docs.walletbeacon.io/guides/sign-payload/#raw)
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/45454460/186629580-0505089c-7359-492a-8669-fc629ed42ad8.png">

**Expected (correct) behavior**
Do not truncate the first character on the hexadecimal representation of the given payload.

**Comment by AndreasGassmann** [comment]
Cutting off the first character seems to be behaviour of Temple wallet.

I tested it with the Beacon debug wallet and AirGap Wallet, both received the full payload.

The solution to this issue is to not use the RAW signing type because the behaviour across wallets is inconsistent. Instead the 05 prefixed approach should be used. I also updated the docs to reflect that. https://docs.walletbeacon.io/guides/sign-payload
