### ISSUE TITLE
Matrix interaction documentation?

### ISSUE THREAD

**Issue by BearCooder** [airgap-it/beacon-sdk#415]
**Summary**
There is not documentation or description about the process. It seems interesting to me and I think useful for others in the future too that want to dive into it. What Rich discovered from a quick glance at the code, the gist of the process is as follows, but is there any published docs on this? If not, could someone confirm or correct the following?

    1. dApp creates a private room in the matrix and gets a token
    2. dApp creates a QR code of the token and displays it to the wallet.
    3. Wallet reads QR code/token and joins the private room
    4. Wallet listens for messages in private room.
    5. dApp send a permission request message to the private room
    6. Wallet reads permission request message and responds with approve/deny
    7. dApps post other messages, operations and transaction messages in private room
    8. Wallet reads and responds to messages.

**Also, where can I find a central list of the messages and the format used for messages posted to the matrix?**
I personally would like to know more about the process.

**Describe your use case**
It all started with re struggling for days (embarrassingly...) to get a React Native wallet to connect to the [test dapp](https://debug.walletbeacon.io/) with partial success. I understand there are some challenges with React Native **but I feel like I shouldn't have to look at the Beacon SDK, Kukai and Umami source code just to get this working!** which is what I've had to do to get this partial success. Is anyone else having this experience or am I just having really bad luck?

**Comment by AndreasGassmann** [comment]
It would definitely be interesting to document the internals of how beacon communicates to the matrix server.

However, this is not relevant to regular users of the SDK because it's an implementation detail and abstracted away from the user for the most part. As an example, the PostMessage transport used with browser extension wallets, or the WC2 transport, work differently, but for the SDK user it's the same flow and the internals don't matter.

We have some diagrams of the flows here, but they are very high level and some are outdated: https://docs.walletbeacon.io/advanced/flows/p2p-direct

Any PR to extend or update them would be highly appreciated.
