### ISSUE TITLE
https://debug.walletbeacon.io/ QR code

### ISSUE THREAD

**Issue by BearCooder** [airgap-it/beacon-sdk#417]
**Describe the bug (current behavior)**
The QR code on https://debug.walletbeacon.io/ contains data that's different from what is copied to the clipboard. The copy/paste doesn't have the tezos://?type=tzip10&data= prefix. I was expecting both the QR code and the copied string to be the same. Is this intentional and what's the reasoning?

And regarding QR code data encoding..
I discovered this by looking at the source code but could not find it in the docs. The QR code data is encoded using bs58check. It's one of those things where I'm looking at a string and need to go on a hunt to understand what it means?

**Comment by AndreasGassmann** [comment]
The data is bs58check encoded because there is no risk that an invalid character ends up in the URL. (eg. through the appMetadata).

The QR code is prefixed with the deeplink in case it's scanned by a phone that has a tezos wallet installed, so the wallet would open automatically. When copying to clipboard (which is mostly a dev option), this is not needed.
