### ISSUE TITLE
Remove Galleon from wallets cause it is not supported

### ISSUE THREAD

**Issue by LauraPlayStables** [airgap-it/beacon-sdk#437]
**Describe the bug (current behavior)**
Hi,
Can you remove Galleon from wallets, cause it is not supported, does not work, and people still try.

Thanks!

**To Reproduce**

**Expected (correct) behavior**

**Screenshots and/or logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment**

- Device: [e.g. iPhone X]
 - OS: [e.g. iOS 14]

**Additional context**

**Comment by AndreasGassmann** [comment]
Due to App Store restrictions, Galleon had to remove certain features from the version that is distributed through the Apple App Store. This also includes the Beacon functionality. However, if the app is downloaded from their website or GitHub, Beacon is still supported and working.

I will close this task because we will now prioritise a related task to completely re-design the pairing alert: https://github.com/airgap-it/beacon-sdk/issues/355
