### ISSUE TITLE
UnknownBeaconError with requestOperation for TezosOperationType.PROPOSALS

### ISSUE THREAD

**Issue by avysel** [airgap-it/beacon-sdk#543]
I have an error using requestOperation with a PROPOSALS operation type:

```
const input: RequestOperationInput = {
    operationDetails: [{
        kind: TezosOperationType.PROPOSALS,
        period: "103",
        proposals: ["ProxfordSW2S7fvchT1Zgj2avb5UES194neRyYVXoaDGvF9egt8"]
    }]
}
const result: OperationResponse = await beaconWallet.client.requestOperation(input);
```

With Temple, I only have this error message:
```
Error
Failed to send operations
```
Difficult to know what happened, the underlying error seems wrapped in this generic message.

But with Kukai, I have this error:
```
{
    "name": "UnknownBeaconError",
    "title": "Error",
    "message": "[UNKNOWN_ERROR]:An unknown error occured. Please try again or report it to a developer.",
    "description": "An unknown error occured. Please try again or report it to a developer."
}
```

I tested with Flextesa, using an active baker account and an injected proposal.
Someone tried it with an active baker on mainnet for current proposal period, with Temple, and also got "Failed to send operations".

**Comment by IsaccoSordo** [comment]
Hi @avysel,
sorry for the late reply.
As you can see in [L303](https://github.com/airgap-it/beacon-sdk/blob/2233b1eed1b28f5d793d55cc037e0be21db509ac/packages/beacon-dapp/src/events.ts#L303) we use `UnknownBeaconError` as a default when the error type is missing and it is not possible to determine what kind of error we are working with.
By the code snippet you have provided, it seems that you are working with beacon through taquito.
Try to reach them out and ask them for confirmation/more info on this topic.
Adding another error event is not a problem however we need to receive a specific type from the wallet side in order to handle it correctly.
Hope this helps you.

**Comment by avysel** [comment]
Ok, thanks. I'll ask them.

**Comment by IsaccoSordo** [comment]
issue closed due to inactivity.
