### ISSUE TITLE
Deeplink pairing not working on mobile for Kukai Web

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#616]
**Describe the bug (current behavior)**
It will open Trust wallet instead of Kukai on iOS.

**To Reproduce**
1. Click 'Request Permission' on the example dapp
2. Click on 'Kukai'

**Expected (correct) behavior**
It should open Kukai wallet, not Trust wallet

**Environment**

- Device: iPhone 13
- OS: iOS 17.0.3
- Browser: Safari

**Additional context**
Branch: feat/transport-kukai-wc2

**Comment by IsaccoSordo** [comment]
Hi @klassare,
the issue was caused by an hardcoded link to Trust wallet.
With #628 now we dynamically generate a WC link based on the selected wallet information.
Relevant lines of code: [alert/index.tsx#L461](https://github.com/airgap-it/beacon-sdk/blob/028c604b3826d3bdb8a570539ddea5f644f2f175/packages/beacon-ui/src/ui/alert/index.tsx#L461)

**Comment by klassare** [comment]
<img width="488" alt="Skärmavbild 2023-11-07 kl  11 34 27" src="https://github.com/airgap-it/beacon-sdk/assets/31806893/114dcbbe-a587-49d4-aba2-a232257aa0fd">
It's not possible for Kukai Web to handle that URI. We need a solution that works for both Kukai Web and mobile.

**Comment by IsaccoSordo** [comment]
Hi @klassare, 
so if I understand correctly you need the possibility to choose between syncing with web wallet and deeplinking, is it correct?

**Comment by AndreasGassmann** [comment]
@klassare I'm not sure if there is a solution that works across all platforms.

On mobile, the most common way to do deeplinking is still the custom scheme, eg. `kukai://`. This works on iOS and Android, but doesn't work on web. On web, it's possible to register custom handlers, but I think they have to start with `web+`, which I'm not sure is compatible with iOS and Android. Plus the user would have to already have visited the website (kukai) before to allow the regstration. https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler

I guess the modern solution would be to use Universal Links on iOS (https://developer.apple.com/ios/universal-links/) and App Links on Android (https://developer.android.com/training/app-links). This should also work in browsers because it can use the same URL.

We can change the behaviour of the alert to use Universal / App Links, you just need to make sure the apps are able to handle them.

There is also the option to have an intermediate page that you own that does the deeplinking according to your custom logic, I think TrustWallet does that under link.trustwallet.com

**Comment by simonmcl** [comment]
Mobile apps shouldn't be forced into using universal links. They are not a replacement to deeplinks, both have their benefits/strengths

When setting up a WC connection, the client is required to supply app metadata. This metadata includes redirect links. Beacon should be reading this and acting accordingly. E.g. if the appmetadata contains a `kukai://` redirect link, then use deeplinks. If not, fallback to web links

Re: the point about 3 `///`. Yes this can cause issues. A third slash should only be added before the `wc2` if the last element of the redirect link is not a slash. E.g.

- redirect: `kukai://` -> no added slash
- redirect: `kukai://app` -> yes added slash
- redirect: `kukai://wc/` -> no added slash

**Comment by IsaccoSordo** [comment]
This is fixed since version [v4.2.0](https://github.com/airgap-it/beacon-sdk/releases/tag/v4.2.0)
