### ISSUE TITLE
Session update not working

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#618]
**Describe the bug (current behavior)**
Session updates are not always handled by Beacon

**To Reproduce**
1. Pair with Kukai from the example dapp
2. Refresh the example dapp
3. Change account in Kukai for the active session

**Expected (correct) behavior**
Session update should be handled correctly

**Environment**

- Device: MacBook Pro
- OS: macOS Sonoma
- Browser: Chrome

**Additional context**
Branch: feat/transport-kukai-wc2

**Comment by IsaccoSordo** [comment]
Hi @klassare,
the issue was caused by the fact that the transports weren't listening to messages immediately after the init phase.
Before #644 we loaded all the transports lazily, in other words whenever a function got executed (requestPermissions, signPayload etc...)  then, and only then, the transports would have been initialised.
What happens now is that we eagerly initialise the transport whenever an account is loaded from localStorage and the transport is not p2p.
Relevant lines of code: [DAppClient.ts#L377-#L383](https://github.com/airgap-it/beacon-sdk/blob/6e2948bcaa38b8117d6d251a0704540764577f5e/packages/beacon-dapp/src/dapp-client/DAppClient.ts#L377-#L383)
