### ISSUE TITLE
Kukai button unresponsive #2

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#624]
**Describe the bug (current behavior)**
Kukai wallet option becomes unresponsive sometimes. 

**To Reproduce**
1. Click 'permission request" and then 'Kukai'

**Expected (correct) behavior**
The Kukai button should never become unresponsive

**Screenshots and/or logs**
<img width="1851" alt="Skärmavbild 2023-10-18 kl  16 37 01" src="https://github.com/airgap-it/beacon-sdk/assets/31806893/b666f1a6-7019-4d8f-8cad-8304ec497a6c">

**Environment**

- Device: MacBook Pro
- OS: macOS Sonoma
- Browser: Chrome

**Additional context**
Branch: feat/transport-kukai-wc2

**Comment by IsaccoSordo** [comment]
Hi @klassare,
This issue belongs to a series of issues related to WalletConnect itself.
In short, signClient client will throw an error whenever an invalid key, topic, expirer etc. is detected.
While we can't remove these errors what we have been doing for the last few months is to improve our error handling to avoid as much as we can "broken states".
Since #542 we've added the following fallbacks:
1. error propagation throughout the transport layer (example: [WalletConnectCommunicationClient.ts#L427-#L456](https://github.com/airgap-it/beacon-sdk/blob/feat/transport-kukai-wc2/packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts#L427-#L456) check out #542 for more details)
2. added detection of invalid/broken state (example [DAppClient.ts#L1751-#L1752](https://github.com/airgap-it/beacon-sdk/blob/feat/transport-kukai-wc2/packages/beacon-dapp/src/dapp-client/DAppClient.ts#L1751-#L1752))
3. clearing localStorage entries whenver we clear beacon internal state: (example [WalletConnectCommunicationClient.ts#L633-#L648](https://github.com/airgap-it/beacon-sdk/blob/feat/transport-kukai-wc2/packages/beacon-transport-walletconnect/src/communication-client/WalletConnectCommunicationClient.ts#L633-#L648))
4. improved connection handling with transport: (example [DAppClient.ts#L590-#L594](https://github.com/airgap-it/beacon-sdk/blob/feat/transport-kukai-wc2/packages/beacon-dapp/src/dapp-client/DAppClient.ts#L590-#L594))

To clarify, the last 3 points are available in the latest build.
Hope this clarifies the situation.

**Comment by IsaccoSordo** [comment]
This issue is solved since [v4.1.1](https://github.com/airgap-it/beacon-sdk/releases/tag/v4.1.1)
