### ISSUE TITLE
Requests sent to wallet with no name

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#625]
**Describe the bug (current behavior)**
In some states the dapp can send requests to a wallet with no name.

**To Reproduce**
1. Pair with Kukai from the example dapp
2. Open the example dapp in a 2th tab
3. Click "reset & refresh" in the 2th tab
4. Go back to the 1st tab and send a request

**Expected (correct) behavior**
It should show an error message if there is no connection with the wallet anymore.

**Screenshots and/or logs**
<img width="873" alt="Skärmavbild 2023-10-18 kl  17 03 18" src="https://github.com/airgap-it/beacon-sdk/assets/31806893/ab16572f-6cf5-40ad-9c3b-a81a8e67f6ac">

**Environment**

- Device: MacBook Pro
- OS: macOS Sonoma
- Browser: Chrome

**Additional context**
Branch: feat/transport-kukai-wc2

**Comment by IsaccoSordo** [comment]
Hi @klassare,
the issue was caused by an internal signClient state misalignment with localStorage.
Namely if you have two DApps, let's say A and B, if you first sync with A and then you reset&refresh with B (note with this action you are clearing storage entries) signClient in A won't notice those changes and therefore a subsequent call to signClient.session.getAll() and signClient.pairing.getAll() will return the old (and now discarded) sessions/pairings
With one of the changes inside #612, we now give more importance to the values stored inside the storage rather than signClient.
Relevant lines of code: 

1. [DAppClient.ts#L1751-#L1752](https://github.com/airgap-it/beacon-sdk/blob/feat/transport-kukai-wc2/packages/beacon-dapp/src/dapp-client/DAppClient.ts#L1751-#L1752)
2. [WalletConnectTransport.ts#L67-#L81](https://github.com/airgap-it/beacon-sdk/blob/feat/transport-kukai-wc2/packages/beacon-transport-walletconnect/src/WalletConnectTransport.ts#L67-#L81)
