### ISSUE TITLE
Destructor not working properly

### ISSUE THREAD

**Issue by klassare** [airgap-it/beacon-sdk#635]
**Describe the bug (current behavior)**
In some situations `client.destroy()` has an inconvenient delay. This can cause issues for logic that depends on the client first being destroyed. For example like with the "reset & refresh" button in the example dapp.

**To Reproduce**
1. Open the example dapp and "Reset & refresh".
2. Pair with Kukai and approve the permission request
3. Send an operation request

**Expected (correct) behavior**
`destroy()` should always resolve within a few seconds

**Environment**

- Device: MacBook Pro
- OS: macOS Sonoma
- Browser: Chrome

**Additional context**
Branch: feat/transport-kukai-wc2

**Comment by AndreasGassmann** [comment]
We investigated this issue and those are the findings:

1. We were not able to reproduce the delay with the `destroy` method. In the past, I feel like the button did at times not properly reset & refresh the page (potentially the delay mentioned here), but after all of the other fixes have been merged, I could no longer reproduce it. I also made a change to the UI to disable the button after clicking it, so we have better visual feedback.
2. The `destroy` method does a couple of things to clean up. Besides removing local storage entries, it also disconnects the transport and waits for this action to be done. The problem is that we can't really control what happens internally, eg. inside the signClient. When we call `await signClient.core.pairing.disconnect({ topic: pairing.topic })`, if this hangs for some reason, then the `await client.destroy()` will also hang. If we don't await everything internally, then we run into the risk that not everything is cleaned up and "ready" when the destroy resolves.

Unless we can reliably reproduce the error and pinpoint exactly what is causing the delay, I think we have to keep it as it is, unless anyone has another suggestion.

BTW: The PR linked in this issue does not directly address this issue, because of the points mentioned above. However, it does address another issue where the destroy method could resolve while not everything was cleaned up internally.

**Comment by klassare** [comment]
Let me share a video where I demonstrate the bug. Notice that the spinner in the dapp tab when the permission request is approved.
![Skärmavbild 2023-11-06 kl  12 37 35](https://github.com/airgap-it/beacon-sdk/assets/31806893/8ee86283-7c0a-49d9-9bf1-cbb4f666b568)

**Comment by klassare** [comment]
It can be reliable reproduced. See video:
https://github.com/airgap-it/beacon-sdk/assets/31806893/0522e0ea-0db2-4f60-9f95-3f354613a601

**Comment by klassare** [comment]
Looks like #639 fixes it
