### ISSUE TITLE
Ability to turn off console logs

### ISSUE THREAD

**Issue by ac10n** [airgap-it/beacon-sdk#656]
For instance, in the file: `packages/beacon-ui/src/ui/alert/index.tsx` in function: `openAlert`, we have:

```
  p2pPayload?.then(() => {
    console.log('P2P LOADED')
  })
  wcPayload?.then(() => {
    console.log('WC LOADED')
  })

  if (isServer) {
    console.log('DO NOT RUN ON SERVER')
    return ''
  }
```

While the last log only happens if something is not right, the first two create logs without the dApp dev's ability to turn them off.

Can we add a config to turn off these logs?
Also, can we turn that config on by default?

**Comment by IsaccoSordo** [comment]
Hi @AlirezaHaghshenas,
thanks for the issue, the logs you mention will be hidden in the upcoming release.
there is already the possibility to show the debug logs by setting `window.beaconSdkDebugEnabled = true` as you can see in https://github.com/airgap-it/beacon-sdk/blob/9bd66991f2424a9bdfe458d264ee08ba8b8086ab/examples/dapp.html#L14
We suggest against turning on that config by default because it was only meant for development.
However nothing can stop you by implementing it in your application 😄
